class ErrorMessages:
    COORDINATES_NOT_FOUND = "COORDINATES_NOT_FOUND"
    GETTING_RESPONSE_FAILED = "GETTING_RESPONSE_FAILED"
    READING_RESPONSE_FAILED = "READING_RESPONSE_FAILED"
    PARSING_DATA_FAILED = "PARSING_DATA_FAILED"