class ErrorMessages:
    COORDINATES_NOT_FOUND = "COORDINATES_NOT_FOUND"
    GETTING_RESPONSE_FAILED = "GETTING_RESPONSE_FAILED"
    READING_RESPONSE_FAILED = "READING_RESPONSE_FAILED"
    PARSING_DATA_FAILED = "PARSING_DATA_FAILED"


class Regions:
    NORTH = 'N'
    CENTRAL_UPPER_EAST = 'C1E'
    CENTRAL_UPPER_WEST = 'C1W'
    CENTRAL_LOWER_EAST = 'C2E'
    CENTRAL_LOWER_WEST = 'C2W'
    SOUTH = 'S'


class CacheIdentifiers:
    FORECAST = 'forecast'


WEATHER_API_URL = 'https://api.openweathermap.org'
